services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - babylonpiles_data:/mnt/babylonpiles/data
      - babylonpiles_piles:/mnt/babylonpiles/piles
    networks:
      - babylonpiles-network
    depends_on:
      - storage
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - babylonpiles-network
    depends_on:
      - backend
    restart: unless-stopped

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      # Primary storage location - configure in storage/Dockerfile
      - babylonpiles_storage:/mnt/hdd1

      # Additional drives (uncomment and customize as needed)
      # - D:\:/mnt/hdd2
      # - E:\:/mnt/hdd3
      # - F:\:/mnt/hdd4

      # Storage container data - now visible in file system
      - babylonpiles_service_data:/app/data
    environment:
      - MAX_DRIVES=1 # Update this to match the number of drives above
      - CHUNK_SIZE=104857600
      - ENABLE_SMART_CHECKS=false # Disable SMART checks for faster startup
      - BACKGROUND_SCAN_INTERVAL=300 # Scan every 5 minutes instead of every minute
    networks:
      - babylonpiles-network
    restart: unless-stopped

  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-tools:latest
    command: /bin/sh -c "kiwix-serve --port=8080 --address=0.0.0.0 /data/*.zim"
    ports:
      - "8081:8080"
    volumes:
      - babylonpiles_piles:/data
    networks:
      - babylonpiles-network
    restart: unless-stopped

volumes:
  babylonpiles_data:
    driver: local
  babylonpiles_piles:
    driver: local
  babylonpiles_storage:
    driver: local
  babylonpiles_service_data:
    driver: local

networks:
  babylonpiles-network:
    driver: bridge
