services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - babylonpiles_data:/mnt/babylonpiles/data
      - babylonpiles_piles:/mnt/babylonpiles/piles
    environment:
      - DATA_DIR=/mnt/babylonpiles/data
      - PILES_DIR=/mnt/babylonpiles/piles
    networks:
      - babylonpiles-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - babylonpiles-network
    depends_on:
      - backend
    restart: unless-stopped

  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-tools:latest
    command: kiwix-serve --port=8080 --address=0.0.0.0 --verbose /data
    ports:
      - "8081:8080"
    volumes:
      - babylonpiles_data:/data
    networks:
      - babylonpiles-network
    restart: unless-stopped

volumes:
  babylonpiles_data:
  babylonpiles_piles:

networks:
  babylonpiles-network:
    driver: bridge 